# Generated by Django 3.0.8 on 2020-09-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20200918_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.BooleanField()),
                ('surname', models.BooleanField()),
                ('group', models.BooleanField()),
            ],
        ),
    ]
